### ISSUE TITLE
after new update mod do nothing

### ISSUE THREAD

**Issue by altairdroid** [emipa606/DynamicCarryingCapacity#3]
i have cleared my mod list so i only have harmony and this mod but when i add anything like bionic arm it does not change mass carried stat, it only stayed at the default 35kg and 28kg, it was fine before update

**Comment by emipa606** [comment]
@Inglix As I do not really know about transpilers, could you look into this?

**Comment by iszyzyzzy** [comment]
I encountered the same issue and, despite having no experience developing RimWorld mods, after researching extensively on the wiki and with the help of ChatGPT, I found that the problem stems from line 14 of MassUtility_Capacity_Patch.cs. This line was modified in a recent commit. I've tested both the original code:
`public static MethodInfo GetPawnBodySizeInfo = AccessTools.Method(typeof(Pawn), "get_BodySize");`
and the AI-suggested code:
`public static readonly MethodInfo GetPawnBodySizeInfo = AccessTools.PropertyGetter(typeof(Pawn), nameof(Pawn.BodySize));`
Both versions seem to work correctly.

**Comment by Inglix** [comment]
@emipa606 The findings by @iszyzyzzy are correct. After merging my pull request it seems you added another commit which changed that line so that it gets the MethodInfo directly from the BodySize property rather than it's getter. The way the transpiler is written this will simply prevent any changes from being made without throwing an error, since it never finds the instruction it's supposed to replace.

Either reverting to the original line I submitted in my pull request (you can still add the `readonly` keyword) or using the alternative one iszyzyzzy suggested should work.

**Comment by emipa606** [comment]
Ill fix it later today

**Comment by emipa606** [comment]
Should be fixed in 7385ee8
Thanks for the report and the help in this!

I try to use `nameof` wherever possible as any breaking code-changes caused whenever Rimworld updates will make it show errors in the IDE instead of during testing.

**Comment by Inglix** [comment]
I technically made the exact same mistake myself while I was originally working on this, by writing in `"BodySize"` instead of `"get_BodySize"` for the name of the method. Took me a while of scratching my head in confusion before I realized what I'd done wrong, which naturally became a facepalm moment.
